import { Game } from '@database/entity/Game';

export const gameArray: Game[] = [
  {
    id: 'c6ca5ded-42f4-4251-9423-55700140b096',
    parentGameId: null,
    title: '"Alone"',
    alternateTitles: '',
    series: '',
    developer: 'Natpat',
    publisher: 'MoFunZone; Sketchy',
    dateAdded: '2019-11-24T23:39:57.629Z',
    dateModified: '2021-03-07T02:08:12.000Z',
    platform: 'Flash',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr: 'Platformer; Puzzle; Pixel',
    source: 'https://www.newgrounds.com/portal/view/578326',
    applicationPath: 'FPSoftware\\Flash\\flashplayer_32_sa.exe',
    launchCommand: 'http://uploads.ungrounded.net/578000/578326_Preloader.swf',
    releaseDate: '2011-08-28',
    version: '',
    originalDescription:
      'Play as a penguin and a tortoise solving puzzles using a jetpack and a gun in this challenging, funky, colourful platformer!\nPlay alongside a beautiful soundtrack with 3 different songs, and funky graphics. Can you beat all 20 levels?\nI\'m so glad I\'m finally getting this out. Finally! :D Enjoy :)',
    language: 'en',
    library: 'arcade',
    orderTitle: '"alone"',
    activeDataId: null,
    activeDataOnDisk: false,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
  {
    id: '6fabbb7a-f614-455c-a239-360b6b69ea24',
    // This is not the real parent game id. It doesn't matter, deal with it.
    parentGameId: 'c6ca5ded-42f4-4251-9423-55700140b096',
    title: '"Game feel" demo',
    alternateTitles: '',
    series: '',
    developer: 'Sebastien Benard',
    publisher: 'Deepnight.net',
    dateAdded: '2021-01-25T23:30:49.267Z',
    dateModified: '2022-04-03T17:37:21.000Z',
    platform: 'HTML5',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr:
      'Demonstration; Action; Platformer; Shooter; Pixel; Side-Scrolling',
    source: 'http://deepnight.net/games/game-feel/',
    applicationPath: 'FPSoftware\\Basilisk-Portable\\Basilisk-Portable.exe',
    launchCommand: 'http://deepnight.net/games/game-feel/',
    releaseDate: '2019-12-19',
    version: '',
    originalDescription:
      'This prototype is not exactly an actual game. It was developed to serve as a demonstration for a “Game feel” talk in 2019 at the ENJMIN school.\n\nIt shows the impact of small details on the overall quality of a game.\n\nYou will need a GAMEPAD to test it. You can enable or disable game features in this demo by pressing the START button.\n\nGAMEPAD is required to play\nA\njump\nB\ndash\nX\nshoot\nSTART\nenable/disable features\nSELECT\nrestart',
    language: 'en',
    library: 'arcade',
    orderTitle: '',
    activeDataId: 8656,
    activeDataOnDisk: false,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
  {
    id: '4b1c582f-c953-48d4-b839-22897adc8406',
    parentGameId: null,
    title: '"Eight Planets and a Dwarf" Sudoku',
    alternateTitles: '',
    series: '',
    developer: 'Julia Genyuk; Dave Fisher',
    publisher: 'Windows to the Universe',
    dateAdded: '2022-02-16T03:34:35.697Z',
    dateModified: '2022-02-16T04:08:14.000Z',
    platform: 'Flash',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr: 'Space; Sudoku',
    source: 'https://www.windows2universe.org/games/sudoku/sudoku.html',
    applicationPath: 'FPSoftware\\Flash\\flashplayer_32_sa.exe',
    launchCommand:
      'http://www.windows2universe.org/games/sudoku/planets_sudoku.swf',
    releaseDate: '',
    version: '',
    originalDescription: '',
    language: 'en',
    library: 'arcade',
    orderTitle: '',
    activeDataId: 96874,
    activeDataOnDisk: true,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
  {
    id: 'f82c01e0-a30e-49e2-84b2-9b45c437eda6',
    parentGameId: null,
    title: '"Mind Realm"',
    alternateTitles: '',
    series: '',
    developer: 'Wisdomchild',
    publisher: 'WET GAMIN',
    dateAdded: '2021-09-03T13:42:06.533Z',
    dateModified: '2021-12-13T02:09:25.000Z',
    platform: 'HTML5',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr: 'Puzzle; Score-Attack; Pixel; Arcade',
    source: 'http://wetgamin.com/mindrealm.php',
    applicationPath: 'FPSoftware\\Basilisk-Portable\\Basilisk-Portable.exe',
    launchCommand: 'http://wetgamin.com/html5/mindrealm/index.html',
    releaseDate: '',
    version: '',
    originalDescription: '',
    language: 'en',
    library: 'arcade',
    orderTitle: '',
    activeDataId: 44546,
    activeDataOnDisk: true,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
  {
    id: 'b7dbd71b-d099-4fdf-9127-6e0a341b7f2d',
    parentGameId: null,
    title: '"Build a Tree" Dendrochronology Activity',
    alternateTitles: '',
    series: '',
    developer: '',
    publisher: 'Windows to the Universe',
    dateAdded: '2022-02-18T04:20:19.301Z',
    dateModified: '2022-02-18T04:31:29.000Z',
    platform: 'Flash',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr: 'Creative; Educational; Object Creator; Toy',
    source:
      'https://www.windows2universe.org/earth/climate/dendrochronology_build_tree.html',
    applicationPath: 'FPSoftware\\Flash\\flashplayer_32_sa.exe',
    launchCommand:
      'http://www.windows2universe.org/earth/climate/images/dendrochronology_build_tree.swf',
    releaseDate: '',
    version: '',
    originalDescription:
      'The interactive diagram below demonstrates a very simple model of tree ring growth.\n\nSelect a temperature range (Normal, Cool, or Warm) and a precipitation amount (Normal, Dry, or Wet) for the coming year. Click the "Add Yearly Growth" button. The tree (which you are viewing a cross-section of the trunk of) grows one year\'s worth, adding a new ring.\n\nAdd some rings while varying the temperature and precipitation. Which of these factors has a stronger influence on the growth of the type of tree being modeled here?\n\nUse the "Reset" button to start over.\n\nThe "Show Specimen Tree" button displays a section of an "actual" tree specimen. Can you model the annual climate during each year of the specimen tree\'s life, matching your diagram with the specimen, to determine the climate history "written" in the rings of the specimen tree? (The "answer" is listed below, lower down on this page).',
    language: 'en',
    library: 'arcade',
    orderTitle: '',
    activeDataId: 97171,
    activeDataOnDisk: false,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
  {
    id: 'a95d0ff7-3ee9-460f-a4f9-0e0c77764d13',
    parentGameId: null,
    title: '!BETA! little bullet hell',
    alternateTitles: '',
    series: '',
    developer: 'leonidoss341',
    publisher: 'Newgrounds',
    dateAdded: '2021-08-04T06:09:06.114Z',
    dateModified: '2021-08-04T06:09:44.000Z',
    platform: 'Flash',
    broken: false,
    extreme: false,
    playMode: 'Single Player',
    status: 'Playable',
    notes: '',
    tagsStr: 'Action; Shooter',
    source: 'https://www.newgrounds.com/portal/view/624363',
    applicationPath: 'FPSoftware\\Flash\\flashplayer_32_sa.exe',
    launchCommand:
      'http://uploads.ungrounded.net/624000/624363_touhou_project_tutorial.swf',
    releaseDate: '2013-08-29',
    version: 'Beta',
    originalDescription:
      'Testing bullets. Just some fun\n\nAuthor Comments:\n\nWARNING! It\'s just beta, no need to say me that you wanna game, please tell me: everything work good or not? Also i want to know about graphic.\nMovement: keys or WASD, Shift-focus, Z-shooting.',
    language: 'en',
    library: 'arcade',
    orderTitle: '',
    activeDataId: 32195,
    activeDataOnDisk: true,
    extras: null,
    extrasName: null,
    message: null,
    tags: [],
    placeholder: false,
    updateTagsStr: new Game().updateTagsStr,
  },
];
