name: Build Status

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - uses: actions/cache@v2
      id: cache
      with:
        path: | 
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
    - name: Install Dependencies
      run: npm install
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        CI: true
    - name: npm build
      run: npm run build:win32 --if-present
      env:
        CI: true
