name: Test Coveralls

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - master
      - develop

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - uses: actions/cache@v2
      id: cache
      with:
        path: | 
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
    - name: Install Dependencies
      run: npm install
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        CI: true
    - name: Run tests
      run: npx jest --coverage --coverageReporters=lcov
      continue-on-error: true
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
