name: Node CI

on: [push]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, release for ${{ matrix.os }}
      run: |
        npm install
        npm run build --if-present
        npm run release
        7z a -r ${{ matrix.os }}.zip dist/*
      env:
        CI: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.os }}.zip
        asset_name: ${{ matrix.os}}.zip
        tag: latest
        overwrite: true
      
