name: Node CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm build
      run: npm run build --if-present
      env:
        CI: true
        
  release:
    name: Release for all platforms
    needs: build
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [win32, linux, darwin]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
      env:
        CI: true
    - name: npm release
      run: npm run release:${{ matrix.arch }}
    - name: Package releases
      run: |
        7z a dist/flashpoint-launcher-${{ matrix.arch }}.zip ./dist/*/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/flashpoint-launcher-${{ matrix.arch }}.zip
        asset_name: flashpoint-launcher-${{ matrix.arch }}.zip
        tag: latest
        overwrite: true
      
