name: Node CI

on: [push]

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x]  

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build for linux
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
        
  release:
    name: Release for all platforms
    needs: build
    runs-on: windows-latest
    
    strategy:
      matrix:
        release-arch: [linux]
        release-path: [flashpoint-launcher-linux-x64]
        
      steps:
      - name: npm release for all platforms
      run: |
        npm run release:${{ matrix.release-arch }}
        cd dist
        dir
        zip -r ${{ matrix.release-path }}.zip ${{ matrix.release-path }}
        dir
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.release-path }}.zip
        asset_name: ${{ matrix.release-path }}.zip
        tag: latest
        overwrite: true
      
