name: Node CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
        
  release:
    name: Release for all platforms
    needs: build
    runs-on: windows-latest
    
    strategy:
      matrix:
        release-arch: [win32, linux]
        release-path: [flashpoint-launcher-win32-ia32, flashpoint-launcher-linux-x64]
        
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: npm release for all platforms
      run: npm run release:${{ matrix.release-arch }}
    - name: Package releases
      run: 7z -a -r dist/${{ matrix.release-path }} dist/${{ matrix.release-path }}/*
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.release-path }}.zip
        asset_name: ${{ matrix.release-path }}.zip
        tag: latest
        overwrite: true
      
