name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop
      - 'release/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}